version: "3"
services:
  simple-todo:
    build:
      context: .
      dockerfile: build/docker/dev/Dockerfile
    volumes:
      - ./:/app/
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - todo-postgres
    env_file:
      - ./.env

  todo-postgres:
    image: "postgis/postgis:13-master"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo

volumes:
    postgres_data: